Update backup_update_copy
added example to pull the source files from an rsync server (and store locally on the disk set)

diff --git a/encrypted-multi-disk-backup/backup_update_copy b/encrypted-multi-disk-backup/backup_update_copy
--- a/encrypted-multi-disk-backup/backup_update_copy
+++ b/encrypted-multi-disk-backup/backup_update_copy
@@ -1,24 +1,22 @@
 #!/bin/bash
-# usage: backup_update_copy [path/]backupsetname_disknum[.lst] [ mountonly | dryrun | nomd5 ]
+# usage: backup_update_copy [pwdfile] [path/]backupsetname_disknum.lst [ mountonly | dryrun | nomd5 ]
 
-bupdir="/volumeSATA1/satashare1-1" ; if [[ ! -d $bupdir ]] ; then bupdir=/mnt ; fi
+# set bupdir: the directory where the unencrypted mounts of the backup disks will appear e.g. ($bupdir/20201118_001)
+#bupdir="/volumeSATA1/satashare1-1"
+bupdir=/volume1/NetBackup
+
+if [[ $1 != *.lst && -f $1 ]] ; then pwdfile=$1 ; shift ; chmod 000 "$pwdfile" ; fi # restrict access just in case one forgot
+
 if [[ ! -d "$bupdir" ]] ; then echo "Backup target directory $bupdir not found - exit" ; exit 1 ; fi
 
-if [[ -f "$1" && $(basename "$1" | sed -e 's/.*\(\....\)$/\1/') = ".lst" ]] ; then
+if [[ $1 == *.lst && -f $1 ]] ; then
 	# assume backup_diskset_copy [path/]backupsetname_disknum.lst [ mountonly | dryrun ]
 	tmpdir=$(dirname "$1")
 	name=$(basename "$1" | sed -e 's/_[0-9][0-9][0-9].lst$//')
 	dn=$(basename "$1" | sed -e 's/.*_\([0-9][0-9][0-9]\).lst$/\1/' -e 's/[0]*//')
-elif [[ -n $(grep ".*_[0-9][0-9][0-9]$" <<< $1) ]] ; then
-	# assume backup_diskset_copy backupsetname_disknum [ mountonly | dryrun ]
-	tmpdir="/volume1/backup_mounts/_backup_sets" ; if [[ ! -d $tmpdir ]] ; then tmpdir="/root/backup_sets" ; fi
-	name=$(basename "$1" | sed -e 's/_[0-9][0-9][0-9]$//')
-	dn=$(basename "$1" | sed -e 's/.*_\([0-9][0-9][0-9]\)$/\1/' -e 's/[0]*//')
 else
-	echo "usage:   $0 [path/]backupsetname_disknum[.lst] [ mountonly | dryrun | nomd5 ]"
-#	echo "         $0 [path/]@backupsetname_disknum@     [ mountonly | dryrun | nomd5 ]"
-	echo "example: $0 20180805_003 mountonly"
-	echo "note:    when mountonly or dryrun is specified, no log file is created and md5 verification is skipped"
+	echo "usage: $0 [pwdfile] [path/]backupsetname_disknum[.lst] [ mountonly | dryrun | nomd5 ]" >&2
+	echo "note:  when mountonly or dryrun is specified, no log file is created and md5 verification is skipped" >&2
 	exit 1
 fi
 
@@ -27,7 +25,7 @@ opts=$2
 #echo "$bupdir # $tmpdir # $name # $dn # $dsk # $opts" ; exit
 
 if [[ ! -d "$bupdir/$dsk" ]] ; then
-	echo "Mounting $dsk"
+	echo "Mounting @$dsk@"
 	mkdir -pv "$bupdir/@$dsk@"
 	mkdir -p  "$bupdir/$dsk"
 	if (( $(df -P | grep "$bupdir/$dsk" | wc -l) == 0 )) ; then
@@ -81,13 +79,20 @@ df -B 1 "$bupdir/$dsk" | tee -a $log # log how much space was deleted / will be 
 echo "Copying $dsk" | tee -a $log
 # copy files with rsync - using rsync also makes it possible to resume copying after the process got aborted
 # note: with --files-from, the -r (--recursive) from -a is not implied (see man page), so if the input list contains directories, only the directory is copied, not its contents (that's how it should be in this case)
-# note: the --delete-before option doesn't seem to work to clean up any rogue files before copying (for instance, when reusing the disk second time 'round and reusing as many files as possible). hence the files are cleaned out with diff
+# note: the --delete-before option doesn't seem to work to clean up any rogue files before copying (for instance, when reusing the disk second time 'round and reusing as many files as possible). hence the files were cleaned out with diff
 flist=$(mktemp) ; grep '^+' "$bdl" | cut -f 5 > $flist
-if [[ $opts = "dryrun" ]] ; then
-	rsync -avn --files-from="$flist" --relative --dirs / "$bupdir/$dsk" | tee -a $log
-else
-	rsync -av --files-from="$flist" --relative --dirs / "$bupdir/$dsk" # no output to log or stdout, only stderr
+if [[ -z $pwdfile ]] ; then
+	tmp=$(mktemp) ; echo -n "Password: " ; read -s pwd ; echo "$pwd" > $tmp ; chmod 000 $tmp ; pwdfile=$tmp
 fi
+if [[ $opts = "dryrun" ]] ; then
+	#rsync -avn --files-from="$flist" --relative --dirs / "$bupdir/$dsk" | tee -a $log
+	rsync -avn --files-from="$flist" --relative --dirs --copy-dirlinks --password-file="$pwdfile" rsync://admin@192.168.2.101/NetBackup "$bupdir/$dsk" | tee -a $log
+else
+	#rsync -av --files-from="$flist" --relative --dirs / "$bupdir/$dsk" # use rsync to copy from and to local filesystem
+	rsync -av --files-from="$flist" --relative --dirs --copy-dirlinks --password-file="$pwdfile" rsync://admin@192.168.2.101/NetBackup "$bupdir/$dsk/" # use rsync to read files from remote server and store on local file system
+	# PS> no output to log or stdout, only stderr
+fi
+if [[ -n $tmp ]] ; then rm $tmp ; fi
 rm $flist
 
 # re-read the disk by calculating the md5 check sums and register the moddate and size
@@ -106,9 +111,9 @@ else
 		echo "Verifying $dsk (save output in $tmpdir/$dsk.md5)" | tee -a $log
 		mkfilelist_md5 "$bupdir/$dsk" | sed -e "s#\t$bupdir/#\t#" > "$tmpdir/$dsk.md5"
 	fi
-	echo "Unmounting $dsk"
-	umount "$bupdir/$dsk"
-	rmdir "$bupdir/$dsk"
+#	echo "Unmounting $dsk"
+#	umount "$bupdir/$dsk"
+#	rmdir "$bupdir/$dsk"
 fi
 echo "Done" | tee -a $log
 
