changed scanning method to make use of mkfilelist_md5 -f (incremental md5 summing)

diff --git a/encrypted-multi-disk-backup/backup_update_copy b/encrypted-multi-disk-backup/backup_update_copy
--- a/encrypted-multi-disk-backup/backup_update_copy
+++ b/encrypted-multi-disk-backup/backup_update_copy
@@ -1,5 +1,5 @@
 #!/bin/bash
-# usage: backup_update_copy [pwdfile] [path/]backupsetname_disknum.lst [ mountonly | dryrun | nomd5 ]
+# usage: backup_update_copy [pwdfile] [path/]backupsetname_disknum.lst [ mountonly | dryrun | md5 [prev_md5_file.md5 ] ]
 
 # set bupdir: the directory where the unencrypted mounts of the backup disks will appear e.g. ($bupdir/20201118_001)
 #bupdir="/volumeSATA1/satashare1-1"
@@ -11,20 +11,25 @@ if [[ ! -d "$bupdir" ]] ; then echo "Backup target directory $bupdir not found -
 
 if [[ $1 == *.lst && -f $1 ]] ; then
 	# assume backup_diskset_copy [path/]backupsetname_disknum.lst [ mountonly | dryrun ]
-	tmpdir=$(dirname "$1")
+	wrkdir=$(dirname "$1")
 	name=$(basename "$1" | sed -e 's/_[0-9][0-9][0-9].lst$//')
 	dn=$(basename "$1" | sed -e 's/.*_\([0-9][0-9][0-9]\).lst$/\1/' -e 's/[0]*//')
+	shift
+	opts=$@
 else
-	echo "usage: $0 [pwdfile] [path/]backupsetname_disknum[.lst] [ mountonly | dryrun | nomd5 ]" >&2
+	echo "usage: $0 [pwdfile] [path/]backupsetname_disknum[.lst] [ mountonly | dryrun | md5 [prev_md5_file.md5 ] ]" >&2
 	echo "note:  when mountonly or dryrun is specified, no log file is created and md5 verification is skipped" >&2
+	echo "note:  the pwdfile is used if the files are fetched with rsync over the network; for local (filesystem)" >&2
+	echo "       rsync, this is not necessary. the copy method is hardcoded in the copy section; two examples are given" >&2
 	exit 1
 fi
 
 dsk=$(printf "%s_%03d" "$name" "$dn")
-opts=$2
-#echo "$bupdir # $tmpdir # $name # $dn # $dsk # $opts" ; exit
+#echo "$bupdir # $wrkdir # $name # $dn # $dsk # $opts" ; exit
 
-if [[ ! -d "$bupdir/$dsk" ]] ; then
+if [[ -d "$bupdir/$dsk" ]] ; then
+	echo "INFO: $bupdir/$dsk exists - assuming it is the mounted backup disk $dsk"
+else
 	echo "Mounting @$dsk@"
 	mkdir -pv "$bupdir/@$dsk@"
 	mkdir -p  "$bupdir/$dsk"
@@ -38,32 +43,37 @@ if [[ ! -d "$bupdir/$dsk" ]] ; then
 fi
 if [[ $opts = "mountonly" ]] ; then exit ; fi
 
-bdl="$tmpdir/$dsk.lst"
+bdl="$wrkdir/$dsk.lst"
 if [[ ! -f "$bdl" ]] ; then echo "Backup todo list $bdl not found - exit" ; exit 1 ; fi
-log="$tmpdir/$dsk.log"
+log="$wrkdir/$dsk.log"
 if [[ $opts = "dryrun" ]] ; then log=/dev/null ; fi # don't overwrite log file in dryrun (could be enabled if necessary)
 
 echo "Creating backup disk $dn from disk set \"$name\" ($bdl) in $bupdir" | tee $log
 if [[ $opts = "dryrun" ]] ; then echo ">>DRY RUN<<" | tee -a $log ; fi
 
-echo "Cleanup $dsk" | tee -a $log
+echo "Deleting files on $dsk" | tee -a $log
 # cleanup of files that are no longer in the copy set
 grep '^-' "$bdl" | cut -f 5 | while read f ; do
 	if [[ $opts = "dryrun" ]] ; then
-		echo "Will remove: $f" | tee -a $log
+		echo "Will remove: $bupdir/$dsk/$f" | tee -a $log
 	else
-		rm "$f" ; # no output to log or stdout, only stderr
+		if [[ ! -f "$bupdir/$dsk/$f" ]] ; then
+			echo "WARNING: can't delete: $f not found on $dsk" | tee -a $log
+		else
+			rm "$bupdir/$dsk/$f" ; # no output to log or stdout, only stderr if rm fails
+		fi
 	fi
 done
 
 echo "Moving and renaming files on $dsk" | tee -a $log
 grep '^[=>]' "$bdl" | while IFS=$'\t' read f1 f1 f3 f4 f5 f6 ; do #
-	if [[ ! -f $f4 ]] ; then echo "ERROR $f4 not found on $dsk" | tee -a $log ; fi # just checking...
-	mkdir -p "$(dirname "$f6")"
+	if [[ ! -f "$bupdir/$dsk/$f4" ]] ; then echo "WARNING: can't move: $f4 not found on $dsk" | tee -a $log ; fi # just checking...
+	if [[   -f "$bupdir/$dsk/$f6" ]] ; then echo "WARNING: can't move: $f6 already exists on $dsk - skipping" | tee -a $log ; continue ; fi # just checking...
+	mkdir -p "$(dirname "$bupdir/$dsk/$f6")"
 	if [[ $opts = "dryrun" ]] ; then
-		echo "Will move: $f4 to $f6" | tee -a $log
+		echo "Will move: $bupdir/$dsk/$f4 to $bupdir/$dsk/$f6" | tee -a $log
 	else
-		mv "$f4" "$f6" ; # no output to log or stdout, only stderr
+		mv "$bupdir/$dsk/$f4" "$bupdir/$dsk/$f6" ; # no output to log or stdout, only stderr
 	fi
 done
 
@@ -76,12 +86,15 @@ else
 fi
 df -B 1 "$bupdir/$dsk" | tee -a $log # log how much space was deleted / will be reused
 
-echo "Copying $dsk" | tee -a $log
+echo "Copying modified and new files to $dsk" | tee -a $log
 # copy files with rsync - using rsync also makes it possible to resume copying after the process got aborted
 # note: with --files-from, the -r (--recursive) from -a is not implied (see man page), so if the input list contains directories, only the directory is copied, not its contents (that's how it should be in this case)
-# note: the --delete-before option doesn't seem to work to clean up any rogue files before copying (for instance, when reusing the disk second time 'round and reusing as many files as possible). hence the files were cleaned out with diff
-flist=$(mktemp) ; grep '^+' "$bdl" | cut -f 5 > $flist
+# note: the --delete-before option doesn't seem to work to clean up any rogue files before copying (for instance, when reusing the disk second time 'round and reusing as many files as possible). hence the files were cleaned out with diff producing the ^- wipe list
+flist=$(mktemp)
+grep -P '^\*' "$bdl" | cut -f 8 >  $flist # the modified files
+grep -P '^\+' "$bdl" | cut -f 5 >> $flist # the new files
 if [[ -z $pwdfile ]] ; then
+	# interactive mode
 	tmp=$(mktemp) ; echo -n "Password: " ; read -s pwd ; echo "$pwd" > $tmp ; chmod 000 $tmp ; pwdfile=$tmp
 fi
 if [[ $opts = "dryrun" ]] ; then
@@ -100,16 +113,20 @@ rm $flist
 # strip the $bupdir base path from the files listed so they start with $dsk/...
 df -B 1 "$bupdir/$dsk" | tee -a $log # log the final utilisation of the disk
 if [[ $opts = "dryrun" ]] ; then
-	echo "Skipping verification (dry run)" | tee -a $log
+	echo "Skipping verification of $bupdir/$dsk to $wrkdir/$dsk.[fst|md5] (dry run)" | tee -a $log
 	# and don't unmount
 else
-	if [[ $opts = "nomd5" ]] ; then
-		echo "Fast scan of $dsk (save output in $tmpdir/$dsk.fst)" | tee -a $log
-		mkfilelist_fast "$bupdir/$dsk" > "$tmpdir/$dsk.fst"
-	else
-		# this is the default
-		echo "Verifying $dsk (save output in $tmpdir/$dsk.md5)" | tee -a $log
-		mkfilelist_md5 "$bupdir/$dsk" > "$tmpdir/$dsk.md5"
+	echo "Fast scan of $dsk (save output in $wrkdir/$dsk.fst)" | tee -a $log
+	mkfilelist_fast "$bupdir/$dsk" | sed -e "s#\t$bupdir/$dsk/#\t#" > "$wrkdir/$dsk.fst"
+	if [[ $opts == md5 ]] ; then
+		# full md5 scan
+		echo "Verifying $dsk (save output in $wrkdir/$dsk.md5)" | tee -a $log
+		mkfilelist_md5 "$bupdir/$dsk" | sed -e "s#\t$bupdir/$dsk/#\t#" > "$wrkdir/$dsk.md5"
+	elif [[ $opts == md5\ * ]] ; then
+		# incremental md5 scan using previous scan
+		prev=${opts#md5 }
+		echo "Verifying $dsk (using previous scan $prev, save output in $wrkdir/$dsk.md5)" | tee -a $log
+		mkfilelist_md5 -f $prev "$bupdir/$dsk" | sed -e "s#\t$bupdir/$dsk/#\t#" > "$wrkdir/$dsk.md5"
 	fi
 #	echo "Unmounting $dsk"
 #	umount "$bupdir/$dsk"
